### PR TITLE
adding file upload data to values in multipart body for ios

### PR DESCRIPTION
**Pull request by sisoje**

### CODE REVIEW

**Comment by BorntraegerMarc** [comment]
This PR is helpful for us because for some file uploads we don't only want to send the file but some additional params

**Comment by guzmanoj** [comment]
Hi @mlynch do we have any estimations regarding this feature? I mean in terms of release.

**Comment by mlynch** [comment]
We're finishing up Capacitor 3 then will be revisiting the PRs/contributions to this repo. Thanks for hanging in there and appreciate the contribution!

**Review by thomasvidas — APPROVED** [review]
LGTM. Holding off on merging until I can check #58 as well so I can get them in around the same

**Pull request merged**
