### PR TITLE
Update to Capacitor v3 and some bug fixes

### PR DESCRIPTION
**Pull request by muuvmuuv**
Decided to create this merge request for any further development. We use our own version in our project because it takes too long for updates to get pushed to npm.

Whats included:

- In the Swift version of `upload` headers weren't included
- Missing type definitions for `uploadFile`
- Simplify `uploadFile`
- Make iOS and Web Version Capacitor 3 ready (Android NOT included, because I don't have any experience with it and we haven't yet deployed to Google Play)

Feel free to use it as a reference or merge it into the cap-3 branch.

Just mention you here because I have seen you already took some effort into making it v3 ready @thomasvidas.

### CODE REVIEW

**Comment by muuvmuuv** [comment]
Here are the patches if one wants to update their local copy too: [patches.zip](https://github.com/capacitor-community/http/files/5797543/patches.zip)

**Comment by thomasvidas** [comment]
This is great! I'll take a look at these. I think the best way to handle npm is to release 1.0.0 when Capacitor 3 hits stable. I can also publish a 0.3.0 for the existing changes that are on master now

**Comment by muuvmuuv** [comment]
Since it is a breaking change I would say v1.0.0 makes the most sense, according to semver.

**Comment by muuvmuuv** [comment]
OK, that was fast! Exciting 🎉

**Pull request merged**
