### PR TITLE
Capacitor 3 Support

### PR DESCRIPTION
**Pull request by thomasvidas**
Draft PR for Capacitor 3 Support

# Android
- [x] Example Updated
- [x] Plugin Updated
- [x] Refactoring / Code Cleanup
  - [x] Cookies
  - [x] Requests

# iOS
- [x] Example Updated
- [x] Plugin Updated
- [x] Refactoring / Code Cleanup
  - [x] Cookies
  - [x] Requests

# Web
- [x] Example Updated
- [x] Plugin Updated
- [x] Refactoring / Code Cleanup
  - [x] Cookies
  - [x] Requests
  
### Example Server
- [x] ESM update
- [x] Update dependencies

### CODE REVIEW

**Comment by muuvmuuv** [comment]
When do you think you will publish a beta on npm? Would love to test the iOS part (partially web too). 😃  Just saw that the version is already bumped.

**Comment by thomasvidas** [comment]
Aiming for the end of this week for both 0.3.0 and 1.0.0-beta on npm 🤞

**Comment by muuvmuuv** [comment]
Thanks for your hard work! Take your time and stay healthy! I don't need it till end of the week ^^.

**Comment by jbagaresgaray** [comment]
Any news on this PR?

**Comment by thomasvidas** [comment]
You can download the Capacitor 3 compatible version using `npm i @capacitor-community/http@next`. I just need to change the tags/branch names but its all working fine

**Comment by najmulansari** [comment]
image

Hi There,
I have upgraded to capacitor 3 today also updated the http plugin "@capacitor-community/http@next", but started getting error in download method. It does not say any specific but error but "Error". Please see the above image. Do you have any idea. In capacitor 2 it used to work fine, but not anymore.

**Comment by thomasvidas** [comment]
If you have an problem, make a GitHub repo with a reproduction of your error and open an issue. A PR is not the appropriate place to get help with this

**Pull request merged**
