### PR TITLE
fix(android): add missing imports

### PR DESCRIPTION
**Pull request by robingenz**
`gradlew build` currently fails with:  

```
> Task :capacitor-community-http:compileDebugJavaWithJavac FAILED
C:\test\node_modules\@capacitor-community\http\android\src\main\java\com\getcapacitor\plugin\http\Http.java:467: error: cannot find symbol
    private void writeToOutputStream(OutputStream out, String data) throws IOException {
                                     ^
  symbol:   class OutputStream
  location: class Http
C:\test\node_modules\@capacitor-community\http\android\src\main\java\com\getcapacitor\plugin\http\Http.java:469: error: cannot find symbol
            os.write(data.getBytes(StandardCharsets.UTF_8));
                                   ^
  symbol:   variable StandardCharsets
  location: class Http
Note: C:\test\node_modules\@capacitor-community\http\android\src\main\java\com\getcapacitor\plugin\http\FilesystemUtils.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
<===----------> 26% EXECUTING [1s]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':capacitor-community-http:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
18 actionable tasks: 1 executed, 17 up-to-date
```

This fix imports the missing references.

### CODE REVIEW

**Comment by lucashsilva** [comment]
I had the same problem and can confirm this works

**Review by thomasvidas — APPROVED** [review]

**Comment by SalahAdDin** [comment]
@thomasvidas is there any change to get this done in a new release version?

**Comment by thomasvidas** [comment]
Yes. Once I handle the outstanding issues and PRs I plan on releasing a 0.3.0 to npm. I can't give you an ETA but I'm trying to get it out soon. You can pull down the `master` branch right now if you need a more immediate fix though.

**Comment by SalahAdDin** [comment]
@thomasvidas the problem with using this repository is it does not include the distribution folder.

**Comment by thomasvidas** [comment]
You can pull down the repo and run the following npm commands to build the `dist` folder

```bash
npm install
npm run build
```

**Comment by SalahAdDin** [comment]
@thomasvidas yeah, we did that, but for production it is not a out-of-the-box idea.

Thanks.

**Comment by SalahAdDin** [comment]
@thomasvidas We did that, but it does not seem intuitive since installing by the repo does not include the **src** folder and pulling down, building, copying and pasting does not seem suitable for a production environment.

Thanks.

**Pull request merged**
