### PR TITLE
Fix for #15 Encode response according to `responseType`

### PR DESCRIPTION
**Pull request by Landschaft**
Instead of just treating all responses as strings, consider `responseType` to properly encoding the data received from the server.

This should fix https://github.com/capacitor-community/http/issues/15

### CODE REVIEW

**Comment by Landschaft** [comment]
This PR is not yet complete; the following is missing:

- Web implementation
- Documentation in Readme

Before I continue fixing the above I'd like to know that you think about my changes @thomasvidas @ProofOfKeags

**Comment by ProofOfKeags** [comment]
I think that the purpose of the changes is well placed. I'm not good enough at the languages involved though to rigorously evaluate the implementation.

**Comment by Landschaft** [comment]
> I think that the purpose of the changes is well placed. I'm not good enough at the languages involved though to rigorously evaluate the implementation.

**Comment by Landschaft** [comment]
> I think that the purpose of the changes is well placed. I'm not good enough at the languages involved though to rigorously evaluate the implementation.

Thanks @ProofOfKeags for having a look at it. Would you be able to implement the _web_ plugin? That's the part where _I_ am not good at.

**Comment by thomasvidas** [comment]
I've added this to the 1.0 milestone. Looks good so far. I don't have the bandwidth to handle this right now but I'll be able to handle web closer to release if no one beats me to it 😄

**Comment by Landschaft** [comment]
@thomasvidas I've added the missing web implementation as well.

**Review by thomasvidas — APPROVED** [review]

**Pull request merged**
